events {
    worker_connections 1024;
}

http {
    upstream comfortspace_backend {
        server api1:80;
        server api2:80;
        server api3:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://comfortspace_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}